-- ЗАДАНИЕ 4.1
-- Show the product with the largest average price over the market.
SELECT PRODUCT.WARE, AVG(PRODUCT.PRICE) AS AVGPRICE
	FROM PRODUCT
GROUP BY PRODUCT.WARE
ORDER BY AVGPRICE DESC
LIMIT 1;

-- ЗАДАНИЕ 4.2
-- Show one sample ware from each category.
SELECT CATEGORY.CLASS, CATEGORY.WARE
	FROM CATEGORY
GROUP BY CATEGORY.CLASS;


-- ЗАДАНИЕ 4.3 
-- Show the most expensive ware in each category and its price
SELECT CATEGORY.CLASS, PRODUCT.WARE, PRODUCT.PRICE
	FROM PRODUCT
JOIN CATEGORY
	ON CATEGORY.WARE = PRODUCT.WARE
GROUP BY CATEGORY.CLASS
	HAVING MAX(PRODUCT.PRICE);

-- ЗАДАНИЕ 4.4
SELECT DISTINCT MANUFACTURER.COMPANY
	FROM MANUFACTURER
EXCEPT
SELECT DISTINCT MANUFACTURER.COMPANY
	FROM MANUFACTURER
JOIN PRODUCT
	ON MANUFACTURER.BILL_ID = PRODUCT.BILL_ID
WHERE PRODUCT.PRICE / (SELECT AVG(PRICE)
												   FROM PRODUCT AS PRODQ
											   WHERE PRODQ.WARE = PRODUCT.WARE) < 1.2;

-- ЗАДАНИЕ 4.5 (1 подзапрос).
-- Show the companies that produce all the wares from any category. Result should contain the company and the category and be sorted by the category. If the company covers multiple categories in such way, there should be multiple rows for this company. To prove that the result is correct enrich it with the additional column showing all the wares in the given category that the given company is actually producing.
SELECT MANUFACTURER.COMPANY, CATEGORY.CLASS,
COUNT(DISTINCT PRODUCT.WARE) AS WARECNT,
WARELIST
	FROM MANUFACTURER
JOIN PRODUCT
	ON MANUFACTURER.BILL_ID = PRODUCT.BILL_ID
JOIN CATEGORY
	ON CATEGORY.WARE = PRODUCT.WARE
JOIN (SELECT *,
		 COUNT(CATEGORY.WARE) AS WAREMAXCNT,
		 GROUP_CONCAT(CATEGORY.WARE) AS WARELIST
			 FROM CATEGORY
		 GROUP BY CATEGORY.CLASS) AS Q_WAREMAXCNT
	ON Q_WAREMAXCNT.CLASS = CATEGORY.CLASS
GROUP BY CATEGORY.CLASS, MANUFACTURER.COMPANY
	HAVING WARECNT >= Q_WAREMAXCNT.WAREMAXCNT
ORDER BY MANUFACTURER.COMPANY;

-- ЗАДАНИЕ 4.6 (1 подзапрос).
-- For each bill of material show the company, all the materials, products, total price of all the products considering their amounts. There must be exactly one row per bill and the result must be ordered by company.
SELECT MANUFACTURER.BILL_ID, MANUFACTURER.COMPANY,
GROUP_CONCAT(DISTINCT MATERIAL.WARE) AS MATLIST,
GROUP_CONCAT(DISTINCT PRODUCT.WARE) AS PRODLIST,
Q_PRODTOTALPRICE.PRODTOTALPRICE
	FROM MANUFACTURER,
(SELECT MANUFACTURER.BILL_ID,
	(PRODUCT.PRICE * PRODUCT.AMOUNT) AS PRODTOTALPRICE
		FROM MANUFACTURER
	JOIN PRODUCT
		ON PRODUCT.BILL_ID = MANUFACTURER.BILL_ID) AS Q_PRODTOTALPRICE
OUTER LEFT JOIN PRODUCT
	ON PRODUCT.BILL_ID = MANUFACTURER.BILL_ID
OUTER LEFT JOIN MATERIAL
	ON MATERIAL.BILL_ID = MANUFACTURER.BILL_ID
WHERE Q_PRODTOTALPRICE.BILL_ID = MANUFACTURER.BILL_ID
GROUP BY MANUFACTURER.BILL_ID
ORDER BY MANUFACTURER.COMPANY;

-- ЗАДАНИЕ 4.7 (ТОЛЬКО множества производства) 
SELECT PRODUCT.WARE,
IIF( Q_MATSETS.MATSETS IS NULL, "∅", GROUP_CONCAT(DISTINCT Q_MATSETS.MATSETS) ) AS MATSETS
	FROM PRODUCT
OUTER LEFT JOIN (SELECT MATERIAL.BILL_ID,
"(" || GROUP_CONCAT(DISTINCT MATERIAL.WARE || " ×" || MATERIAL.AMOUNT) || ")" AS MATSETS
	FROM MATERIAL
GROUP BY MATERIAL.BILL_ID) AS Q_MATSETS
	ON Q_MATSETS.BILL_ID = PRODUCT.BILL_ID
GROUP BY PRODUCT.WARE;

-- ЗАДАНИЕ 4.7 (ТОЛЬКО побочные продукты)
SELECT PRODUCT.WARE,
GROUP_CONCAT(DISTINCT Q_ALLPROD.ALLPROD) AS BYPRODUCTS
	FROM PRODUCT
JOIN PRODUCT AS PROD2
	ON PROD2.WARE = PRODUCT.WARE
JOIN (SELECT PRODUCT.BILL_ID,
		  PRODUCT.WARE AS ALLPROD
			  FROM PRODUCT) AS Q_ALLPROD
	ON PROD2.BILL_ID = Q_ALLPROD.BILL_ID
WHERE Q_ALLPROD.ALLPROD <> PRODUCT.WARE
GROUP BY PRODUCT.WARE;


-- ЗАДАНИЕ 4.8 (1 подзапрос).
-- Show all the companies with the largest number of different wares they producing and their lists of wares in alphabetical order.
SELECT MANUFACTURER.COMPANY,
Q_WARECNT.WARECNT,
-- (SELECT DISTINCT GROUP_CONCAT(PRODUCT.WARE)
-- 								 FROM PRODUCT
-- 							 ORDER BY PRODUCT.WARE ASC) AS WARELIST
GROUP_CONCAT(DISTINCT PRODUCT.WARE) AS WARELIST
	FROM MANUFACTURER
JOIN PRODUCT
	ON MANUFACTURER.BILL_ID = PRODUCT.BILL_ID
JOIN (SELECT COUNT(DISTINCT PRODUCT.WARE) AS WARECNT
			  FROM MANUFACTURER
		  JOIN PRODUCT
			  ON MANUFACTURER.BILL_ID = PRODUCT.BILL_ID
		  GROUP BY MANUFACTURER.COMPANY) AS Q_WARECNT
GROUP BY MANUFACTURER.COMPANY
	HAVING COUNT(DISTINCT PRODUCT.WARE) = MAX(Q_WARECNT.WARECNT)
ORDER BY MANUFACTURER.COMPANY ASC;	-- that's all folks!
