--2.1
SELECT DISTINCT MANUFACTURER.COMPANY AS MANUFACTURER
FROM MANUFACTURER
INNER JOIN PRODUCT
ON MANUFACTURER.BILL_ID = PRODUCT.BILL_ID
WHERE PRODUCT.WARE = 'Drinking water'
ORDER BY MANUFACTURER;
--2.2
SELECT DISTINCT COMPANY, PRODUCT.WARE
FROM MANUFACTURER
JOIN PRODUCT ON MANUFACTURER.BILL_ID = PRODUCT.BILL_ID
JOIN CATEGORY ON PRODUCT.WARE = CATEGORY.WARE
WHERE CATEGORY.CLASS = "Raw food"
ORDER BY PRODUCT.WARE, COMPANY;
--2.3
SELECT DISTINCT PRODUCT.WARE
FROM PRODUCT
JOIN MATERIAL ON PRODUCT.BILL_ID = MATERIAL.BILL_ID
JOIN CATEGORY ON MATERIAL.WARE = CATEGORY.WARE
WHERE CATEGORY.CLASS = 'Mineral'
ORDER BY PRODUCT.WARE;
--2.4
SELECT DISTINCT MANUFACTURER.COMPANY
FROM CATEGORY, PRODUCT, MANUFACTURER
WHERE CATEGORY.CLASS LIKE "FUEL" AND PRODUCT.WARE == CATEGORY.WARE
INTERSECT
SELECT DISTINCT MANUFACTURER.COMPANY
FROM CATEGORY, PRODUCT, MANUFACTURER
WHERE CATEGORY.CLASS LIKE "FOOD" AND PRODUCT.WARE == CATEGORY.WARE
--2.5
SELECT DISTINCT MAN1.COMPANY, PROD1.WARE, PROD2.WARE
	FROM MANUFACTURER AS MAN1
INNER JOIN PRODUCT AS PROD1
	ON MAN1.BILL_ID = PROD1.BILL_ID
INNER JOIN CATEGORY AS CAT1
	ON CAT1.WARE = PROD1.WARE
	AND CAT1.CLASS = "Food"
INNER JOIN MANUFACTURER AS MAN2
	ON MAN1.COMPANY = MAN2.COMPANY
INNER JOIN PRODUCT AS PROD2
	ON MAN2.BILL_ID = PROD2.BILL_ID
INNER JOIN CATEGORY AS CAT2
	ON CAT2.WARE = PROD2.WARE
	AND CAT2.CLASS = "Fuel"
WHERE MAN1.COMPANY == MAN2.COMPANY;
--2.6
SELECT DISTINCT MANUFACTURER.COMPANY
FROM CATEGORY fst, CATEGORY snd, PRODUCT, MANUFACTURER
WHERE fst.WARE<>snd.WARE AND fst.CLASS == snd.CLASS AND (PRODUCT.WARE == fst.WARE OR PRODUCT.WARE == snd.WARE) AND PRODUCT.BILL_ID==MANUFACTURER.BILL_ID
ORDER BY MANUFACTURER.COMPANY ASC
--2.7
SELECT DISTINCT PRODUCT.WARE
FROM CATEGORY, PRODUCT
WHERE CATEGORY.CLASS LIKE "MINERAL" AND PRODUCT.WARE == CATEGORY.WARE
EXCEPT
SELECT DISTINCT PRODUCT.WARE
FROM CATEGORY, PRODUCT
WHERE CATEGORY.CLASS NOT LIKE "MINERAL" AND PRODUCT.WARE == CATEGORY.WARE
ORDER BY PRODUCT.WARE ASC
--2.8
SELECT DISTINCT MANUFACTURER.COMPANY
FROM MANUFACTURER
JOIN PRODUCT AS Product1 ON MANUFACTURER.BILL_ID = Product1.BILL_ID
JOIN MATERIAL AS Material1 ON Product1.WARE = Material1.WARE
JOIN PRODUCT AS Product2 ON Material1.BILL_ID = Product2.BILL_ID
ORDER BY COMPANY;
--2.9
SELECT DISTINCT MAN1.COMPANY,
	IIF(MAT1.WARE IS NULL, "[[nothing]]", MAT1.WARE) ||	-- Inline IF -- if/then/else "в строчку"
	" -> " || PROD1.WARE || " -> " || PROD2.WARE
	FROM MANUFACTURER AS MAN1
OUTER LEFT JOIN MATERIAL AS MAT1
	ON MAN1.BILL_ID = MAT1.BILL_ID	-- получаем только для вывода
INNER JOIN PRODUCT AS PROD1
	ON MAN1.BILL_ID = PROD1.BILL_ID
INNER JOIN MANUFACTURER AS MAN2
	ON MAN1.COMPANY = MAN2.COMPANY
INNER JOIN PRODUCT AS PROD2
	ON MAN2.BILL_ID = PROD2.BILL_ID
INNER JOIN MATERIAL AS MAT2
	ON MAN2.BILL_ID = MAT2.BILL_ID
	AND PROD1.WARE = MAT2.WARE
ORDER BY PROD1.WARE ASC;
